# this sets up a database to host the data
version: '3.8'
services:

  rikstoto-warehouse:
    image: postgres
    networks:
      - rikstoto-warehouse-network
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rikstoto
    volumes:
      - rikstoto-warehouse-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # database admin gui
  adminer:
    image: adminer
    networks:
      - rikstoto-warehouse-network
    restart: always
    ports:
      - 8090:8080

volumes:
  rikstoto-warehouse-volume: {}

networks:
  rikstoto-warehouse-network: {}
